//! The curated site table: data only.
//!
//! `sites.rs` holds everything that reads it, and the tests there hold every
//! entry to the contract: a host exactly as `site_identity` normalizes one,
//! listed once, a valid local label, a taxonomy category other than
//! `UNLOGGED`, and the category of any browser-context rule that names the
//! host.
//!
//! A host is listed only when one category is right for the large majority of
//! a knowledge worker's visits to it. Mixed-use hosts (news, shopping, banking,
//! portals, shorteners, blogging platforms) are left out on purpose, so they
//! reach local inference and the "needs a category" list instead of a
//! confident wrong answer. A longer listed host beats a `WithSubdomains`
//! parent, which is how help and developer hosts under a product stay
//! REFERENCE.

use super::sites::{SiteScope, SiteSeed};

#[rustfmt::skip]
pub(crate) const SITE_SEEDS: &[SiteSeed] = &[
    // Communication
    // -- Google Workspace
    SiteSeed { host: "mail.google.com", scope: SiteScope::HostOnly, label: "communication:gmail", category: "COMMUNICATION" },
    SiteSeed { host: "gmail.com", scope: SiteScope::HostOnly, label: "communication:gmail", category: "COMMUNICATION" },
    SiteSeed { host: "calendar.google.com", scope: SiteScope::HostOnly, label: "communication:calendar", category: "COMMUNICATION" },
    SiteSeed { host: "meet.google.com", scope: SiteScope::HostOnly, label: "meeting:meet", category: "COMMUNICATION" },
    SiteSeed { host: "chat.google.com", scope: SiteScope::HostOnly, label: "communication:chat", category: "COMMUNICATION" },
    SiteSeed { host: "messages.google.com", scope: SiteScope::HostOnly, label: "communication:chat", category: "COMMUNICATION" },
    SiteSeed { host: "voice.google.com", scope: SiteScope::HostOnly, label: "communication:chat", category: "COMMUNICATION" },
    // -- Microsoft 365
    SiteSeed { host: "outlook.office.com", scope: SiteScope::HostOnly, label: "communication:outlook", category: "COMMUNICATION" },
    SiteSeed { host: "outlook.office365.com", scope: SiteScope::HostOnly, label: "communication:outlook", category: "COMMUNICATION" },
    SiteSeed { host: "outlook.live.com", scope: SiteScope::HostOnly, label: "communication:outlook", category: "COMMUNICATION" },
    SiteSeed { host: "outlook.cloud.microsoft", scope: SiteScope::HostOnly, label: "communication:outlook", category: "COMMUNICATION" },
    SiteSeed { host: "outlook.com", scope: SiteScope::HostOnly, label: "communication:outlook", category: "COMMUNICATION" },
    SiteSeed { host: "teams.microsoft.com", scope: SiteScope::HostOnly, label: "meeting:teams", category: "COMMUNICATION" },
    SiteSeed { host: "teams.live.com", scope: SiteScope::HostOnly, label: "meeting:teams", category: "COMMUNICATION" },
    SiteSeed { host: "teams.cloud.microsoft", scope: SiteScope::HostOnly, label: "meeting:teams", category: "COMMUNICATION" },
    // -- Chat
    SiteSeed { host: "slack.com", scope: SiteScope::WithSubdomains, label: "communication:slack", category: "COMMUNICATION" },
    SiteSeed { host: "discord.com", scope: SiteScope::WithSubdomains, label: "communication:discord", category: "COMMUNICATION" },
    SiteSeed { host: "discord.gg", scope: SiteScope::HostOnly, label: "communication:discord", category: "COMMUNICATION" },
    SiteSeed { host: "web.whatsapp.com", scope: SiteScope::HostOnly, label: "communication:chat", category: "COMMUNICATION" },
    SiteSeed { host: "web.telegram.org", scope: SiteScope::HostOnly, label: "communication:telegram", category: "COMMUNICATION" },
    SiteSeed { host: "messenger.com", scope: SiteScope::WithSubdomains, label: "communication:chat", category: "COMMUNICATION" },
    SiteSeed { host: "app.element.io", scope: SiteScope::HostOnly, label: "communication:chat", category: "COMMUNICATION" },
    SiteSeed { host: "zulipchat.com", scope: SiteScope::WithSubdomains, label: "communication:chat", category: "COMMUNICATION" },
    SiteSeed { host: "cliq.zoho.com", scope: SiteScope::HostOnly, label: "communication:chat", category: "COMMUNICATION" },
    SiteSeed { host: "app.ringcentral.com", scope: SiteScope::HostOnly, label: "communication:chat", category: "COMMUNICATION" },
    // -- Video meetings
    SiteSeed { host: "zoom.us", scope: SiteScope::WithSubdomains, label: "meeting:zoom", category: "COMMUNICATION" },
    SiteSeed { host: "zoom.com", scope: SiteScope::WithSubdomains, label: "meeting:zoom", category: "COMMUNICATION" },
    SiteSeed { host: "webex.com", scope: SiteScope::WithSubdomains, label: "meeting:video", category: "COMMUNICATION" },
    SiteSeed { host: "gotomeeting.com", scope: SiteScope::WithSubdomains, label: "meeting:video", category: "COMMUNICATION" },
    SiteSeed { host: "meet.goto.com", scope: SiteScope::HostOnly, label: "meeting:video", category: "COMMUNICATION" },
    SiteSeed { host: "whereby.com", scope: SiteScope::WithSubdomains, label: "meeting:video", category: "COMMUNICATION" },
    SiteSeed { host: "meet.jit.si", scope: SiteScope::HostOnly, label: "meeting:video", category: "COMMUNICATION" },
    SiteSeed { host: "gather.town", scope: SiteScope::WithSubdomains, label: "meeting:video", category: "COMMUNICATION" },
    SiteSeed { host: "meeting.zoho.com", scope: SiteScope::HostOnly, label: "meeting:video", category: "COMMUNICATION" },
    // -- Async video messages sent to the person (Loom): communication, not viewing
    SiteSeed { host: "loom.com", scope: SiteScope::WithSubdomains, label: "communication:chat", category: "COMMUNICATION" },
    // -- Email
    SiteSeed { host: "mail.proton.me", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "mail.protonmail.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "fastmail.com", scope: SiteScope::WithSubdomains, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "mail.superhuman.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "mail.yahoo.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "mail.aol.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "mail.zoho.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "app.hey.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "app.tuta.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "mail.missiveapp.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "app.frontapp.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    SiteSeed { host: "app.shortwave.com", scope: SiteScope::HostOnly, label: "communication:email", category: "COMMUNICATION" },
    // -- Calendars and scheduling
    SiteSeed { host: "calendar.proton.me", scope: SiteScope::HostOnly, label: "communication:calendar", category: "COMMUNICATION" },
    SiteSeed { host: "calendar.zoho.com", scope: SiteScope::HostOnly, label: "communication:calendar", category: "COMMUNICATION" },
    SiteSeed { host: "calendly.com", scope: SiteScope::WithSubdomains, label: "communication:calendar", category: "COMMUNICATION" },
    SiteSeed { host: "cal.com", scope: SiteScope::WithSubdomains, label: "communication:calendar", category: "COMMUNICATION" },

    // Focus work
    // -- Documents, spreadsheets and slides
    SiteSeed { host: "docs.google.com", scope: SiteScope::HostOnly, label: "document:docs", category: "FOCUS_WORK" },
    SiteSeed { host: "sheets.google.com", scope: SiteScope::HostOnly, label: "document:sheets", category: "FOCUS_WORK" },
    SiteSeed { host: "slides.google.com", scope: SiteScope::HostOnly, label: "document:slides", category: "FOCUS_WORK" },
    SiteSeed { host: "keep.google.com", scope: SiteScope::HostOnly, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "officeapps.live.com", scope: SiteScope::WithSubdomains, label: "document:edit", category: "FOCUS_WORK" },
    SiteSeed { host: "word.cloud.microsoft", scope: SiteScope::HostOnly, label: "document:word", category: "FOCUS_WORK" },
    SiteSeed { host: "excel.cloud.microsoft", scope: SiteScope::HostOnly, label: "document:excel", category: "FOCUS_WORK" },
    SiteSeed { host: "powerpoint.cloud.microsoft", scope: SiteScope::HostOnly, label: "document:powerpoint", category: "FOCUS_WORK" },
    SiteSeed { host: "loop.cloud.microsoft", scope: SiteScope::HostOnly, label: "document:write", category: "FOCUS_WORK" },
    // -- HostOnly: calendar.notion.so and mail.notion.so are not writing
    SiteSeed { host: "notion.so", scope: SiteScope::HostOnly, label: "document:notion", category: "FOCUS_WORK" },
    SiteSeed { host: "coda.io", scope: SiteScope::WithSubdomains, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "quip.com", scope: SiteScope::WithSubdomains, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "craft.do", scope: SiteScope::WithSubdomains, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "roamresearch.com", scope: SiteScope::WithSubdomains, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "hackmd.io", scope: SiteScope::WithSubdomains, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "evernote.com", scope: SiteScope::HostOnly, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "app.grammarly.com", scope: SiteScope::HostOnly, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "overleaf.com", scope: SiteScope::WithSubdomains, label: "document:overleaf", category: "FOCUS_WORK" },
    SiteSeed { host: "typst.app", scope: SiteScope::WithSubdomains, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "writer.zoho.com", scope: SiteScope::HostOnly, label: "document:write", category: "FOCUS_WORK" },
    SiteSeed { host: "sheet.zoho.com", scope: SiteScope::HostOnly, label: "document:sheets", category: "FOCUS_WORK" },
    SiteSeed { host: "show.zoho.com", scope: SiteScope::HostOnly, label: "document:slides", category: "FOCUS_WORK" },
    SiteSeed { host: "pitch.com", scope: SiteScope::WithSubdomains, label: "document:slides", category: "FOCUS_WORK" },
    SiteSeed { host: "gamma.app", scope: SiteScope::WithSubdomains, label: "document:slides", category: "FOCUS_WORK" },
    // -- Design, whiteboards, diagrams and CAD
    SiteSeed { host: "figma.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "canva.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "miro.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "framer.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "webflow.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "sketch.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "penpot.app", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "excalidraw.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "tldraw.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "app.diagrams.net", scope: SiteScope::HostOnly, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "draw.io", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "lucid.app", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "whimsical.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "app.mural.co", scope: SiteScope::HostOnly, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "photopea.com", scope: SiteScope::WithSubdomains, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "express.adobe.com", scope: SiteScope::HostOnly, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "photoshop.adobe.com", scope: SiteScope::HostOnly, label: "design:visual", category: "FOCUS_WORK" },
    SiteSeed { host: "app.spline.design", scope: SiteScope::HostOnly, label: "design:3d", category: "FOCUS_WORK" },
    SiteSeed { host: "cad.onshape.com", scope: SiteScope::HostOnly, label: "design:cad", category: "FOCUS_WORK" },
    SiteSeed { host: "tinkercad.com", scope: SiteScope::WithSubdomains, label: "design:cad", category: "FOCUS_WORK" },
    // -- Code editors, notebooks and app builders
    SiteSeed { host: "vscode.dev", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "codesandbox.io", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "stackblitz.com", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "replit.com", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "colab.research.google.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "play.rust-lang.org", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "app.hex.tech", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "cloud.databricks.com", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "azuredatabricks.net", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "app.snowflake.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "web.postman.co", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "bolt.new", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "lovable.dev", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "v0.dev", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "v0.app", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    // -- Cloud and developer consoles the person operates
    SiteSeed { host: "console.aws.amazon.com", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "console.cloud.google.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "console.firebase.google.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "portal.azure.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "vercel.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "app.netlify.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "dash.cloudflare.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "dashboard.heroku.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "dashboard.render.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "cloud.digitalocean.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "cloud.mongodb.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "datadoghq.com", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "sentry.io", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "grafana.net", scope: SiteScope::WithSubdomains, label: "document:code", category: "FOCUS_WORK" },
    SiteSeed { host: "appstoreconnect.apple.com", scope: SiteScope::HostOnly, label: "document:code", category: "FOCUS_WORK" },

    // Reference
    // -- Search
    SiteSeed { host: "google.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "google.co.uk", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "google.ca", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "google.com.au", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "google.co.in", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "google.de", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "bing.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "duckduckgo.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "search.brave.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "kagi.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    // -- AI assistants
    SiteSeed { host: "chatgpt.com", scope: SiteScope::WithSubdomains, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "chat.openai.com", scope: SiteScope::HostOnly, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "claude.ai", scope: SiteScope::WithSubdomains, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "perplexity.ai", scope: SiteScope::WithSubdomains, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "gemini.google.com", scope: SiteScope::HostOnly, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "aistudio.google.com", scope: SiteScope::HostOnly, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "notebooklm.google.com", scope: SiteScope::HostOnly, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "copilot.microsoft.com", scope: SiteScope::HostOnly, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "chat.mistral.ai", scope: SiteScope::HostOnly, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "chat.deepseek.com", scope: SiteScope::HostOnly, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "grok.com", scope: SiteScope::WithSubdomains, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "poe.com", scope: SiteScope::WithSubdomains, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "you.com", scope: SiteScope::WithSubdomains, label: "reference:ai_assistant", category: "REFERENCE" },
    SiteSeed { host: "elicit.com", scope: SiteScope::WithSubdomains, label: "reference:ai_assistant", category: "REFERENCE" },
    // -- Code hosting, read and reviewed
    SiteSeed { host: "github.com", scope: SiteScope::WithSubdomains, label: "reference:github", category: "REFERENCE" },
    SiteSeed { host: "raw.githubusercontent.com", scope: SiteScope::HostOnly, label: "reference:github", category: "REFERENCE" },
    SiteSeed { host: "github.io", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "gitlab.com", scope: SiteScope::WithSubdomains, label: "reference:gitlab", category: "REFERENCE" },
    SiteSeed { host: "gitlab.io", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "bitbucket.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "codeberg.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "googlesource.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "huggingface.co", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    // -- Q&A and tech discussion (house precedent: Stack Overflow, Hacker News)
    SiteSeed { host: "stackoverflow.com", scope: SiteScope::WithSubdomains, label: "reference:stack_overflow", category: "REFERENCE" },
    SiteSeed { host: "stackexchange.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "superuser.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "serverfault.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "askubuntu.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "news.ycombinator.com", scope: SiteScope::HostOnly, label: "reference:hacker_news", category: "REFERENCE" },
    SiteSeed { host: "lobste.rs", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    // -- Language, framework and platform documentation
    SiteSeed { host: "developer.mozilla.org", scope: SiteScope::HostOnly, label: "reference:mdn", category: "REFERENCE" },
    SiteSeed { host: "developer.apple.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "docs.rs", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "crates.io", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "rust-lang.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "tokio.rs", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "python.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "pypi.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "readthedocs.io", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "readthedocs.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "npmjs.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "nodejs.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "typescriptlang.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "react.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "reactnative.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "nextjs.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "vuejs.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "angular.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "svelte.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "tailwindcss.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "vite.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "playwright.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "go.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "kotlinlang.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "spring.io", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "apache.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "swift.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "swiftpackageindex.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "cppreference.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "php.net", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "rubygems.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "rubyonrails.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "djangoproject.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "fastapi.tiangolo.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "numpy.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "pydata.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "scikit-learn.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "pytorch.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "tensorflow.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "flutter.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "pub.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "postgresql.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "sqlite.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "hub.docker.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "kubernetes.io", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "git-scm.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "brew.sh", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "archlinux.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "man7.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "devdocs.io", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "w3schools.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "geeksforgeeks.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "caniuse.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "css-tricks.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "web.dev", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "w3.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "whatwg.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "ietf.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "gitbook.io", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "learning.oreilly.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    // -- Vendor documentation and help centres
    SiteSeed { host: "docs.aws.amazon.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "aws.amazon.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "cloud.google.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "developers.google.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "firebase.google.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "ai.google.dev", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "support.google.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "learn.microsoft.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "code.visualstudio.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "platform.openai.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "developers.cloudflare.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "docs.netlify.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "devcenter.heroku.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "docs.digitalocean.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    // -- Help and developer hosts under a seeded parent (the longer host wins)
    SiteSeed { host: "api.slack.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "support.discord.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "developers.zoom.us", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "support.zoom.us", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "support.zoom.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "view.officeapps.live.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "help.figma.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "docs.datadoghq.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "docs.sentry.io", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "developer.okta.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "help.okta.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "support.1password.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "developer.1password.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    // -- File browsers (house precedent: Google Drive and Dropbox are REFERENCE)
    SiteSeed { host: "drive.google.com", scope: SiteScope::HostOnly, label: "document:drive", category: "REFERENCE" },
    SiteSeed { host: "dropbox.com", scope: SiteScope::HostOnly, label: "document:drive", category: "REFERENCE" },
    SiteSeed { host: "app.box.com", scope: SiteScope::HostOnly, label: "document:drive", category: "REFERENCE" },
    SiteSeed { host: "workdrive.zoho.com", scope: SiteScope::HostOnly, label: "document:drive", category: "REFERENCE" },
    SiteSeed { host: "contacts.google.com", scope: SiteScope::HostOnly, label: "reference:contacts", category: "REFERENCE" },
    // -- Encyclopedias, dictionaries and translation
    SiteSeed { host: "wikipedia.org", scope: SiteScope::WithSubdomains, label: "reference:wikipedia", category: "REFERENCE" },
    SiteSeed { host: "wikimedia.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "wiktionary.org", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "britannica.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "merriam-webster.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "dictionary.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "thesaurus.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "dictionary.cambridge.org", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "wordreference.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "deepl.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "translate.google.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "wolframalpha.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "web.archive.org", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "statista.com", scope: SiteScope::WithSubdomains, label: "reference:read", category: "REFERENCE" },
    SiteSeed { host: "books.google.com", scope: SiteScope::HostOnly, label: "reference:read", category: "REFERENCE" },
    // -- Research papers and scholarly search
    SiteSeed { host: "scholar.google.com", scope: SiteScope::HostOnly, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "patents.google.com", scope: SiteScope::HostOnly, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "arxiv.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "biorxiv.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "ncbi.nlm.nih.gov", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "jstor.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "semanticscholar.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "researchgate.net", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "sciencedirect.com", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "link.springer.com", scope: SiteScope::HostOnly, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "nature.com", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "science.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "onlinelibrary.wiley.com", scope: SiteScope::HostOnly, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "academic.oup.com", scope: SiteScope::HostOnly, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "ieeexplore.ieee.org", scope: SiteScope::HostOnly, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "dl.acm.org", scope: SiteScope::HostOnly, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "plos.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "frontiersin.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "mdpi.com", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "ssrn.com", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "openreview.net", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "aclanthology.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "neurips.cc", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "mlr.press", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "nejm.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },
    SiteSeed { host: "zotero.org", scope: SiteScope::WithSubdomains, label: "reference:research", category: "REFERENCE" },

    // Task management
    // -- *.atlassian.net is left out: Jira and Confluence share each workspace's
    //    host, so the host cannot tell a ticket from a document. A workspace goes
    //    to the "needs a category" list and the person decides it once.
    SiteSeed { host: "jira.com", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "linear.app", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "trello.com", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "app.asana.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "app.clickup.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "monday.com", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "height.app", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "app.shortcut.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "todoist.com", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "ticktick.com", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "app.any.do", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "basecamp.com", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "wrike.com", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "teamwork.com", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "app.plane.so", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "youtrack.cloud", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "aha.io", scope: SiteScope::WithSubdomains, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "app.smartsheet.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "app.sunsama.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "app.usemotion.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "tasks.google.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "tasks.office.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "planner.cloud.microsoft", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "to-do.office.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "to-do.live.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },
    SiteSeed { host: "projects.zoho.com", scope: SiteScope::HostOnly, label: "task:manage", category: "TASK_MANAGEMENT" },

    // Social feed
    SiteSeed { host: "reddit.com", scope: SiteScope::WithSubdomains, label: "social:reddit", category: "SOCIAL_FEED" },
    SiteSeed { host: "redd.it", scope: SiteScope::HostOnly, label: "social:reddit", category: "SOCIAL_FEED" },
    SiteSeed { host: "x.com", scope: SiteScope::WithSubdomains, label: "social:x", category: "SOCIAL_FEED" },
    SiteSeed { host: "twitter.com", scope: SiteScope::WithSubdomains, label: "social:x", category: "SOCIAL_FEED" },
    SiteSeed { host: "instagram.com", scope: SiteScope::WithSubdomains, label: "social:instagram", category: "SOCIAL_FEED" },
    // -- HostOnly: business.facebook.com and developers.facebook.com are not the feed
    SiteSeed { host: "facebook.com", scope: SiteScope::HostOnly, label: "social:facebook", category: "SOCIAL_FEED" },
    SiteSeed { host: "m.facebook.com", scope: SiteScope::HostOnly, label: "social:facebook", category: "SOCIAL_FEED" },
    SiteSeed { host: "web.facebook.com", scope: SiteScope::HostOnly, label: "social:facebook", category: "SOCIAL_FEED" },
    SiteSeed { host: "threads.net", scope: SiteScope::WithSubdomains, label: "social:threads", category: "SOCIAL_FEED" },
    SiteSeed { host: "threads.com", scope: SiteScope::WithSubdomains, label: "social:threads", category: "SOCIAL_FEED" },
    // -- linkedin.com is left out: messaging, jobs, Sales Navigator and Learning
    //    share the feed's host, and Learning is a path the host cannot see. A
    //    LinkedIn visit goes to the "needs a category" list and the person
    //    decides it once.
    SiteSeed { host: "bsky.app", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "pinterest.com", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "tumblr.com", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "nextdoor.com", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "truthsocial.com", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "lemmy.world", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "mastodon.social", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "mastodon.online", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "hachyderm.io", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "fosstodon.org", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },
    SiteSeed { host: "infosec.exchange", scope: SiteScope::WithSubdomains, label: "social:feed", category: "SOCIAL_FEED" },

    // Passive consumption
    SiteSeed { host: "youtube.com", scope: SiteScope::WithSubdomains, label: "video:youtube", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "youtu.be", scope: SiteScope::HostOnly, label: "video:youtube", category: "PASSIVE_CONSUMPTION" },
    // -- TikTok follows the house app seed (video:tiktok, PASSIVE_CONSUMPTION)
    SiteSeed { host: "tiktok.com", scope: SiteScope::WithSubdomains, label: "video:tiktok", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "netflix.com", scope: SiteScope::WithSubdomains, label: "video:netflix", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "twitch.tv", scope: SiteScope::WithSubdomains, label: "video:twitch", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "kick.com", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "disneyplus.com", scope: SiteScope::WithSubdomains, label: "video:disney", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "hulu.com", scope: SiteScope::WithSubdomains, label: "video:hulu", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "max.com", scope: SiteScope::WithSubdomains, label: "video:max", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "hbomax.com", scope: SiteScope::WithSubdomains, label: "video:max", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "primevideo.com", scope: SiteScope::WithSubdomains, label: "video:prime", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "tv.apple.com", scope: SiteScope::HostOnly, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "peacocktv.com", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "paramountplus.com", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "crunchyroll.com", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "tubitv.com", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "pluto.tv", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "fubo.tv", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "mubi.com", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "plex.tv", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "dailymotion.com", scope: SiteScope::WithSubdomains, label: "video:streaming", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "open.spotify.com", scope: SiteScope::HostOnly, label: "audio:spotify", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "music.apple.com", scope: SiteScope::HostOnly, label: "audio:music", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "podcasts.apple.com", scope: SiteScope::HostOnly, label: "audio:listen", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "music.amazon.com", scope: SiteScope::HostOnly, label: "audio:music", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "soundcloud.com", scope: SiteScope::WithSubdomains, label: "audio:music", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "pandora.com", scope: SiteScope::WithSubdomains, label: "audio:music", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "deezer.com", scope: SiteScope::WithSubdomains, label: "audio:music", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "tidal.com", scope: SiteScope::WithSubdomains, label: "audio:music", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "bandcamp.com", scope: SiteScope::WithSubdomains, label: "audio:music", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "iheart.com", scope: SiteScope::WithSubdomains, label: "audio:music", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "pocketcasts.com", scope: SiteScope::WithSubdomains, label: "audio:listen", category: "PASSIVE_CONSUMPTION" },
    SiteSeed { host: "overcast.fm", scope: SiteScope::WithSubdomains, label: "audio:listen", category: "PASSIVE_CONSUMPTION" },

    // System
    // -- Account, sign-in and SSO pages
    SiteSeed { host: "accounts.google.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "myaccount.google.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "passwords.google.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "myactivity.google.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "takeout.google.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "one.google.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "admin.google.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "appleid.apple.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "account.apple.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "idmsa.apple.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "iforgot.apple.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "login.microsoftonline.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "login.microsoft.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "login.live.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "account.microsoft.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "account.live.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "myaccount.microsoft.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "mysignins.microsoft.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "myapps.microsoft.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "admin.microsoft.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "portal.manage.microsoft.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "signin.aws.amazon.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "awsapps.com", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "id.atlassian.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "accounts.zoho.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "account.proton.me", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "accounts.firefox.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "auth.openai.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "okta.com", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "oktapreview.com", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "okta-emea.com", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "onelogin.com", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "duosecurity.com", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    // -- Password managers (house precedent: the 1Password app is SYSTEM)
    SiteSeed { host: "1password.com", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "1password.eu", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "vault.bitwarden.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    // -- Router admin pages and connection tests
    SiteSeed { host: "routerlogin.net", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "orbilogin.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "tplinkwifi.net", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "speedtest.net", scope: SiteScope::WithSubdomains, label: "system:manage", category: "SYSTEM" },
    SiteSeed { host: "fast.com", scope: SiteScope::HostOnly, label: "system:manage", category: "SYSTEM" },
];
