//! The behavioural layer: the frozen feature contract, the two segmentation
//! models that read it, and the retention that bounds the durable substrate
//! underneath.
//!
//! The feature contract was published *before* either model existed, per
//! `03-BEHAVIORAL-ENGINE-SPEC.md` § 1, so the online detector and the nightly
//! segmenter cannot quietly disagree about what an observation is — and so the
//! not-identifiable list is on the record before there is any pressure to
//! promote a latent variable into a product claim.
//!
//! # Everything here is shadow
//!
//! [`bocpd`] and [`hmm`] compute numbers. Neither has a caller in the shipped
//! path, neither can reach the drift gate, the delivery path, or any copy
//! surface, and neither changes what a user sees or when they are interrupted.
//! That is not a phase — it is the property that makes it safe to ship an
//! unvalidated model at all. `03` § 5 and `09-RISKS-AND-KILLS.md` both turn on
//! it.
//!
//! [`candidates`] and [`antecedents`] are the same: the miner has no caller,
//! writes only to `antecedent_finding`, and is read only by tests. Nothing it
//! computes can reach a copy surface, and the database's own trigger makes
//! surfacing an unconfirmed finding an `ABORT` rather than a review comment.
//!
//! # The two models have different jobs, and collapsing them is the mistake
//!
//! [`bocpd`] is online, per work block, and answers "did the regime change in
//! the last three runs". [`hmm`] is offline, nightly, over the user's whole
//! history, and answers "which of three states was each run in". They have
//! different latency requirements and different sample-size regimes; one model
//! doing both would be wrong for both.
//!
//! # What they are validated on
//!
//! Synthetic traces with known ground truth, in
//! `tests/behavior_segmentation.rs`, against fixtures generated by
//! `scripts/generate_traces.py`. No real user has ever touched either model.
//! Every number either produces is a claim about the model on data whose truth
//! was known in advance, and it is not evidence about people.

pub mod antecedents;
pub mod bocpd;
pub mod candidates;
pub mod features;
pub mod hmm;
pub mod retention;

pub use retention::OutOfBlockRunRetentionTarget;

#[cfg(test)]
mod tests {
    /// The two models each restate the category cardinality as a compile-time
    /// constant, because a Dirichlet over the wrong number of categories is
    /// wrong silently. This is the seam where a taxonomy that grew without them
    /// growing with it fails loudly instead.
    #[test]
    fn every_model_agrees_with_the_feature_contract_about_the_vocabulary() {
        assert_eq!(
            super::features::CATEGORIES.len(),
            super::bocpd::CATEGORY_COUNT
        );
        assert_eq!(
            super::features::CATEGORIES.len(),
            super::hmm::CATEGORY_COUNT
        );
        assert_eq!(
            super::features::CATEGORIES.len(),
            super::candidates::CATEGORY_COUNT
        );
    }

    /// The candidate registry embeds category NAMES in its stable ids, so it
    /// needs more than the cardinality to match — a reordering would silently
    /// repoint every stored finding at a different antecedent.
    #[test]
    fn the_candidate_registry_uses_the_feature_contracts_category_names_in_order() {
        assert_eq!(
            super::features::CATEGORIES,
            super::candidates::CATEGORIES,
            "the candidate registry and the frozen feature contract disagree \
             about the category vocabulary or its order; every stored \
             candidate_id built from a category name is now ambiguous"
        );
    }

    /// The antecedent layer's horizon is the feature contract's proximal
    /// horizon. Two different notions of "shortly afterwards" would make the
    /// antecedent layer and the decision log incomparable.
    #[test]
    fn the_antecedent_horizon_is_the_proximal_outcome_horizon() {
        assert_eq!(
            super::candidates::HORIZON_SECONDS,
            super::features::PROXIMAL_OUTCOME_HORIZON_SECONDS
        );
    }

    /// `d_t` has one definition. The clip in `bocpd::log_dwell` is the feature
    /// contract's clip, which is Swift's clip. Three names, one number, and
    /// this is the assertion that keeps it that way.
    #[test]
    fn the_dwell_clip_has_exactly_one_definition() {
        assert_eq!(
            super::bocpd::DWELL_CLIP_SECONDS,
            f64::from(super::features::DWELL_CLIP_SECONDS)
        );
        let clipped = super::bocpd::log_dwell(f64::from(super::features::DWELL_CLIP_SECONDS));
        assert!((clipped - super::bocpd::log_dwell(100_000.0)).abs() < 1e-12);
    }
}
